### ISSUE TITLE
Building package and accessibility auto-suggestion

### ISSUE THREAD

**Issue by gnulinux666** [onboard-osk/onboard#2]
**Arch Linux
Gnome 46**

./setup.py build
    tools/install_gsettings_schema
```
cp: cannot create regular file '/usr/share/glib-2.0/schemas/org.onboard.gschema.xml': Permission denied
cp: cannot create regular file '/usr/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override': Permission denied
Failed to create file “/usr/share/glib-2.0/schemas/gschemas.compiled.HLVZP2”: Permission denied
```

**Comment by dr-ni** [comment]
Hi gnulinux666,
is sudo needed?
`sudo /setup.py build`
can you check this:
`ls /usr/share/glib*`

**Comment by gnulinux666** [comment]
Hi dr-ni
I checked with `sudo` privilege and without .
`ls /usr/share/glib*`
dtds  gettext  schemas	valgrind

**Comment by dr-ni** [comment]
and `sudo python3 setup.py build` ?

**Comment by gnulinux666** [comment]
/home/gnulinux/onboard/./setup.py:118: SyntaxWarning: invalid escape sequence '\d'
  version = re.search('(?:(?:\d+)\.)+\d+', output).group()
/home/gnulinux/onboard/./setup.py:55: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  current_ver = version.StrictVersion(DistUtilsExtra.auto.__version__)
/home/gnulinux/onboard/./setup.py:56: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  required_ver = version.StrictVersion('2.12')
removing __pycache__ directories recursively
found dconf version 0.40.0
setup.py: running pkg-config: pkg-config --libs --cflags gdk-3.0 x11 xi xtst xkbfile dconf libcanberra hunspell libudev
setup.py: -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/dconf -D_REENTRANT -I/usr/include/hunspell -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -pthread -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/fribidi -lgdk-3 -lz -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lX11 -lXi -lXtst -lxkbfile -ldconf -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lcanberra -lhunspell-1.7 -ludev
WARNING: the following files are not recognized by DistUtilsExtra.auto:
  Onboard/manual_tests/test_xembed

**Comment by dr-ni** [comment]
is this the full output?
`sudo python3 setup.py clean`
`python3 setup.py build  > build_log.txt 2>&1`
`cat build_log.txt `

**Comment by gnulinux666** [comment]
[build_log.txt](https://github.com/user-attachments/files/15889308/build_log.txt)

**Comment by dr-ni** [comment]
I have commited some fixes...
can you check again:

`git pull`
`sudo python3 setup.py clean`
`python3 setup.py build  > build_log.txt 2>&1`
`cat build_log.txt `
`sudo tools/install_gsettings_schema`

**Comment by gnulinux666** [comment]
[build_log.txt](https://github.com/user-attachments/files/15896129/build_log.txt)
./onboard
/home/gnulinux/onboard/Onboard/utils.py:151: SyntaxWarning: invalid escape sequence '\d'
  """
/home/gnulinux/onboard/Onboard/utils.py:220: SyntaxWarning: invalid escape sequence '\s'
  pattern = re.compile('>\n\s+([^<>\s].*?)\n\s+</', re.DOTALL)
/home/gnulinux/onboard/Onboard/utils.py:221: SyntaxWarning: invalid escape sequence '\g'
  pretty_xml = pattern.sub('>\g<1></', ugly_xml)
/home/gnulinux/onboard/Onboard/utils.py:356: SyntaxWarning: invalid escape sequence '\:'
  """
/home/gnulinux/onboard/Onboard/utils.py:1683: SyntaxWarning: invalid escape sequence '\w'
  """(?:
09:38:15.334 WARNING Config: Starting in project directory, importing local packages and extensions.
Traceback (most recent call last):
  File "/home/gnulinux/onboard/./onboard", line 35, in <module>
    from Onboard.OnboardGtk import OnboardGtk as Onboard
  File "/home/gnulinux/onboard/Onboard/OnboardGtk.py", line 48, in <module>
    from Onboard.Keyboard        import Keyboard
  File "/home/gnulinux/onboard/Onboard/Keyboard.py", line 45, in <module>
    from Onboard.KeyboardPopups        import TouchFeedback
  File "/home/gnulinux/onboard/Onboard/KeyboardPopups.py", line 256, in <module>
    class LabelPopup(KeyboardPopupDrawable):
  File "/home/gnulinux/onboard/Onboard/KeyboardPopups.py", line 264, in LabelPopup
    _osk_util = osk.Util()
                ^^^^^^^^
AttributeError: module 'Onboard.osk' has no attribute 'Util'

**Comment by dr-ni** [comment]
did you make the git pull?
first `cd onboard`
then `git pull`

**Comment by gnulinux666** [comment]
yes I did , although I did  `rm -rf onboard` and `git clone https://github.com/dr-ni/onboard` again

**Comment by dr-ni** [comment]
the distutils warning is solved:
https://github.com/dr-ni/onboard/commit/5a3c7fe41af2113559e3242b1e5585fd2b65b571
but still in your log in line 1:
`/home/gnulinux/onboard/setup.py:55: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.`

**Comment by dr-ni** [comment]
oh sorry there are many more imports let me check it again...

**Comment by dr-ni** [comment]
can you check again:

git pull 
python3 setup.py clean 
python3 setup.py build
sudo tools/install_gsettings_schema

`./onboard` currently cannot start onboard
but if everything worked without errors you can install:

sudo python3 setup.py install

And if necessary, uninstall with
sudo python3 setup.py install --record files.txt
sudo xargs -a files.txt --delimiter='\n' rm -v
sudo rm -rf /usr/local/share/onboard

on my ubuntu I had to install python3-packaging is there also a package for arch?

**Comment by dr-ni** [comment]
and to avoid crashing:

onboard-settings

![Bildschirmfoto zu 2024-06-20 03-21-36](https://github.com/dr-ni/onboard/assets/68241100/1b15527f-8509-408b-ae5a-3dff6d278fe9)

**Comment by gnulinux666** [comment]
[build_log.txt](https://github.com/user-attachments/files/15916909/build_log.txt)
in fact I have ubuntu 24.04 on my real system .
if I sure "suggestion" part work and don't crash I will compile and install in ubuntu.

**Comment by dr-ni** [comment]
your log is looking fine
is it working on your arch after install?

on my 24.04 it was first crashing since the preset is always Xinput
this must be set to gtk until I have made a fix

**Comment by gnulinux666** [comment]
unfortunately it is not working on arch , I set to GTK .

onboard
23:24:06.544 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
23:24:08.112 WARNING Onboard.WPEngine: System language model '/usr/share/onboard/models/.lm' doesn't exist, skipping.
Segmentation fault (core dumped)

**Comment by dr-ni** [comment]
do you have installed mousetweaks?
did you uninstall all previously installed onboard packages?

**Comment by gnulinux666** [comment]
after installing mousetweaks
onboard
23:47:14.112 WARNING Onboard.WPEngine: System language model '/usr/share/onboard/models/.lm' doesn't exist, skipping.
Segmentation fault (core dumped)

I uninstalled and reinstalled but this error remained .

**Comment by dr-ni** [comment]
there is no older onboard installed?
can you install my mousetweaks version?

**Comment by gnulinux666** [comment]
This command `sudo rm -rf /usr/local/share/onboard` remove all onboard from my system .  I installed with this command `sudo pacman -S mousetweaks`

**Comment by dr-ni** [comment]
are you sure onboard is removed correct?
https://bbs.archlinux.org/viewtopic.php?id=96523
what is your displaymanager?
wayland is not supported, you need xorg
can you uninstall mousetweaks and install my git version?

**Comment by gnulinux666** [comment]
in xorg works but "suggestion" is not working yet.

mousetweaks --help-all 
Usage:
  mousetweaks [OPTION?] - GNOME mouse accessibility daemon

Help Options:
  -h, --help                            Show help options
  --help-all                            Show all help options
  --help-gtk                            Show GTK+ Options

GTK+ Options
  --class=CLASS                         Program class as used by the window manager
  --name=NAME                           Program name as used by the window manager
  --gtk-module=MODULES                  Load additional GTK+ modules
  --g-fatal-warnings                    Make all warnings fatal

Application Options:
  --dwell                               Enable dwell click
  --ssc                                 Enable simulated secondary click
  --dwell-time=[0.2-3.0]                Time to wait before a dwell click
  --ssc-time=[0.5-3.0]                  Time to wait before a simulated secondary click
  -m, --dwell-mode=[window|gesture]     Set the active dwell mode
  -c, --hide-ctw                        Hide the click-type window
  -t, --threshold=[0-30]                Ignore small pointer movements
  -g, --geometry=WIDTHxHEIGHT+X+Y       Click-type window geometry
  -s, --shutdown                        Shut down mousetweaks
  --daemonize                           Start mousetweaks as a daemon
  --login                               Start mousetweaks in login mode
  --display=DISPLAY                     X display to use

**which version of mousetweak do you want to install ?**

**Comment by dr-ni** [comment]
please check `ps -e | grep tty`
and `pgrep wayland`

in the README.md you can find the link to my mousetweaks.git

before installation please check again that you have absolutely COMPLETELY unstalled ALL onboard and mousetweaks packages from pacman!

**Comment by dr-ni** [comment]
as I have seen here:
https://wiki.archlinux.org/title/GNOME
Wayland is default

Wayland is not supported, you need xorg


what is your setting?

**Comment by gnulinux666** [comment]
ps -e | grep tty
   1053 tty2     00:00:00 gdm-x-session
   1055 tty2     00:02:44 Xorg
   1093 tty2     00:00:00 gnome-session-b
[gnulinux@arch onboard]$ pgrep wayland

sudo pacman -Rsn mousetweaks
checking dependencies...

Packages (1) mousetweaks-3.32.0-2

Total Removed Size:  0.41 MiB

:: Do you want to remove these packages? [Y/n] y
:: Processing package changes...
(1/1) removing mousetweaks                                 [################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Compiling GSettings XML schema files...

your mousetweaks version get error I've sent log that page

**Comment by dr-ni** [comment]
can you also uninstall onboard from pacman again ?

**Comment by gnulinux666** [comment]
error: target not found: onboard
pacman not found onboard

**Comment by gnulinux666** [comment]
all errors are gone but suggestion is not working and when I close :
onboard
Segmentation fault (core dumped)

**Comment by dr-ni** [comment]
what do you mean with suggestion?
how did you close?
is onboard now working?
is mousetweaks now working?

**Comment by dr-ni** [comment]
maybe you can show me with `recordmydesktop`

**Comment by gnulinux666** [comment]
onboard
22:07:47.524 WARNING Onboard.WPEngine: Failed to find language models in '/home/gnulinux/.local/share/onboard/models': No such file or directory (2)
Segmentation fault (core dumped)

**Comment by gnulinux666** [comment]
[arch-screen0.webm](https://github.com/dr-ni/onboard/assets/173131158/4b873c8f-24b1-4d3d-a7f4-1aae8fb20f9c)

**Comment by dr-ni** [comment]
can you launch it with `onboard -d all`
and send me output after crash

**Comment by gnulinux666** [comment]
[onboard_DEBUG.txt](https://github.com/user-attachments/files/15968995/onboard_DEBUG.txt)

**Comment by gnulinux666** [comment]
Now I'm in Ubuntu noble 24.04  I wanna test it on ubuntu.

**Comment by gnulinux666** [comment]
I installed on ubuntu show suggestion but when I cilicked a word it didn't put on target ,look at screenshot I click sudo on suggestion but don't type in terminal .
![screen-2024-06-25-13-56-14](https://github.com/dr-ni/onboard/assets/173131158/2d46f1bb-1b7b-4deb-81e6-20b92bfca8c7)

**Comment by dr-ni** [comment]
I have now started to fix all deprecated warnings. can you;
git pull
cd onboard/
python3 setup.py clean 
python3 setup.py build 
killall onboard 
sudo python3 setup.py install
and check again 
also onboard-settings
and switch to XInput again

**Comment by gnulinux666** [comment]
Not working ,after now I am going to test it just in ubuntu noble.
[onboard_DEBUG2.txt](https://github.com/user-attachments/files/15973280/onboard_DEBUG2.txt)

**Comment by dr-ni** [comment]
is it starting with the gtk setting?

**Comment by gnulinux666** [comment]
yes, Dose suggestion part work for you? you have ubuntu OS.

**Comment by dr-ni** [comment]
Unfortunately not, I have the same behaviour.
Is the word suggestion working on arch?

**Comment by gnulinux666** [comment]
Not working on arch ,after upgrading python 3.12 word suggestion' onboard not working on ubuntu 22.04 is working.

**Comment by dr-ni** [comment]
for me it is also not working on ubuntu?

can yo show me with recordmydesktop

**Comment by gnulinux666** [comment]
I said on ubuntu 24.04 is not working on ubuntu 22.04 is working .

**Comment by dr-ni** [comment]
ah ok

**Comment by gnulinux666** [comment]
can you install old ubuntu on virtualbox and compare onboard code .
[lubuntu-screen0.webm](https://github.com/dr-ni/onboard/assets/173131158/20f3dcef-c3a0-429f-bbe9-dd4fd5355d9b)

**Comment by dr-ni** [comment]
Theese questions are still not answered:

- Is the XInput crash a problem of the OS or a problem of Onboard or only a wrong preset?
- Is the 'suggestion' problem a gtk-only problem - the ubuntu behaviour is like longpressing on the suggestion?
- why is the 'suggestion' problem on arch different than to ubuntu?

**Comment by dr-ni** [comment]
![image](https://github.com/dr-ni/onboard/assets/68241100/b1145431-a3f7-49a9-9572-7ccfa0ceb032)


Can you check these settings?
It fixed the autosuggestion for me.

**Comment by gnulinux666** [comment]
yes,It fixed for me too , but only work with english language .

**Comment by gnulinux666** [comment]
autosuggestion list these language for example there is no persian .
![screen-2024-06-29-16-43-53](https://github.com/dr-ni/onboard/assets/173131158/24bb6e76-85a7-4d43-bdc0-01323a535518)

**Comment by dr-ni** [comment]
did you install the language?

```
uwe@rp64:~/onboard $ sudo apt install hunspell-de

hunspell                   hunspell-en-us             hunspell-ml
hunspell-af                hunspell-en-za             hunspell-mn
hunspell-an                hunspell-es                hunspell-ne
hunspell-ar                hunspell-eu                hunspell-nl
hunspell-be                hunspell-fr                hunspell-no
hunspell-bg                hunspell-fr-classical      hunspell-oc
hunspell-bn                hunspell-fr-comprehensive  hunspell-pl
hunspell-bo                hunspell-fr-revised        hunspell-pt-br
hunspell-br                hunspell-gd                hunspell-pt-pt
hunspell-bs                hunspell-gl                hunspell-ro
hunspell-ca                hunspell-gl-es             hunspell-ru
hunspell-cs                hunspell-gu                hunspell-si
hunspell-da                hunspell-gug               hunspell-sk
hunspell-de-at             hunspell-he                hunspell-sl
hunspell-de-at-frami       hunspell-hi                hunspell-sr
hunspell-de-ch             hunspell-hr                hunspell-sv
hunspell-de-ch-frami       hunspell-hu                hunspell-sv-se
hunspell-de-de             hunspell-id                hunspell-sw
hunspell-de-de-frami       hunspell-is                hunspell-te
hunspell-de-med            hunspell-it                hunspell-th
hunspell-dz                hunspell-kk                hunspell-tools
hunspell-el                hunspell-kmr               hunspell-tr
hunspell-en-au             hunspell-ko                hunspell-uk
hunspell-en-ca             hunspell-lo                hunspell-uz
hunspell-en-gb             hunspell-lt                hunspell-vi
hunspell-en-med            hunspell-lv            
```

**Comment by dr-ni** [comment]
Is your language in the onboard/models folder?

**Comment by gnulinux666** [comment]
No,my language is not model folder

**Comment by dr-ni** [comment]
are all suggested languages working?

**Comment by gnulinux666** [comment]
I sent a photo, all languages in photo are working ,It's equal language in the onboard/models folder

**Comment by dr-ni** [comment]
did you ever use persian language on onboard before?

**Comment by gnulinux666** [comment]
yes

**Comment by dr-ni** [comment]
on which system?

**Comment by gnulinux666** [comment]
Ubuntu 22.04 and old distribution

**Comment by dr-ni** [comment]
can you check the contents of /usr/local/lib/python3.*/dist-packages/
and search the models folder on that system?

**Comment by gnulinux666** [comment]
It doesn't not depend on that ,in this system works

![screen-2024-06-29-18-06-17](https://github.com/dr-ni/onboard/assets/173131158/a736fe16-9f6d-424c-8f7b-af193f2e419c)

**Comment by dr-ni** [comment]
is persian language working here?
can you show a screen?

**Comment by gnulinux666** [comment]
onboard learns persian then types 

[lubuntu-screen0.webm](https://github.com/dr-ni/onboard/assets/173131158/fe8caa25-540c-42ad-bed6-bef2ea3c69e9)

**Comment by dr-ni** [comment]
I wanted a screenshot of the languages from onboard

**Comment by gnulinux666** [comment]
![VirtualBox_lubuntu_29_06_2024_18_46_54](https://github.com/dr-ni/onboard/assets/173131158/8b75a49d-279e-4518-93b1-e36f5d18c5ce)
![VirtualBox_lubuntu_29_06_2024_18_47_15](https://github.com/dr-ni/onboard/assets/173131158/561302fe-3bba-4b37-a479-03efc885f9fc)

**Comment by dr-ni** [comment]
Ah ok, as I could see in the movie before, you are using the english model and using persian language settings in system.Did you install persian on 24.04 ? Can you write in persian?

**Comment by gnulinux666** [comment]
yes I can write persian on ubuntu 24.04

**Comment by dr-ni** [comment]
can you check my onboard v1.4.2 on 22.04, is the persian suggestion working same way with xinput and gtk on it?

**Comment by gnulinux666** [comment]
Hello @dr-ni , I have lubuntu 20.04 on virtualbox for testing and it has python 3.8 . I checked ,your onboard needs dependencies .

**Comment by dr-ni** [comment]
Which dependencies? Can you install those from readme?
First git pull

**Comment by gnulinux666** [comment]
I have ubuntu 24.04 on my system would please focus on latest ubuntu

**Comment by dr-ni** [comment]
I wantet to find out if the problem is in my onboard version or in ubuntu.

**Comment by gnulinux666** [comment]
These problems happen after upgrading python to 3.12 on new ubuntu . your onboard not supports old python.
[build_log_py3_8.txt](https://github.com/user-attachments/files/16083023/build_log_py3_8.txt)

**Comment by dr-ni** [comment]
the build_log was without any problem?

**Comment by gnulinux666** [comment]
WARNING: the following files are not recognized by DistUtilsExtra.auto:

**Comment by dr-ni** [comment]
this is on every build, because of the autodetection...
my build completed with 0 errors and 0 warnings
you should be able to install
...follow the README

**Comment by gnulinux666** [comment]
on lubuntu 20.04 your onboard works GTK & XInput , and autosuggestion works even with persian language

**Comment by gnulinux666** [comment]
by the way key stroke generator is on auto.

**Comment by dr-ni** [comment]
so my v1.4.2 is working on 20.04 without any problem?
also if you change the keystroke-generator?

**Comment by gnulinux666** [comment]
persian language didn't work AT-SPI key stroke.

**Comment by dr-ni** [comment]
ok, so we have found the problem, can you check all others?

**Comment by gnulinux666** [comment]
in the others XTest & uinput persian and English language are working , then I checked Ubuntu 24.04  it didn't work. Do you change code should I git pull on 24.04?

**Comment by dr-ni** [comment]
yes allways pull clean and build and install 
then check all keystroke-generators

**Comment by gnulinux666** [comment]
same as before

**Comment by dr-ni** [comment]
I do not know the exact reason for that but thinking the problem is in at-spi
can you check https://www.freedesktop.org/wiki/Accessibility/AT-SPI2/
and try to get some help there?

**Comment by gnulinux666** [comment]
Sorry, I don't have experience about professional programing.

**Comment by dr-ni** [comment]
please check this
```
git clone https://git.debian.org/git/pkg-a11y/check-a11y
cd check-a11y
./troubleshoot
```
on both systems
are there differences?

**Comment by gnulinux666** [comment]
just this part
```
Info
INFO: session type 'x11'
INFO: VT ''
INFO: session desktop 'ubuntu-xorg'
INFO: current desktop 'ubuntu:GNOME'
INFO: display variables DISPLAY=:0 
```
```
Info
INFO: session type 'x11'
INFO: VT  '1'
INFO: session desktop ''
INFO: current desktop 'LXQT'
INFO: display variables DISPLAY=:0 
```

**Comment by dr-ni** [comment]
which is which system?
no warnings?

**Comment by gnulinux666** [comment]
first ubuntu 24.04
second lubuntu 20.04

the warning is same on both :
WARN: org.a11y.Status ScreenReaderEnabled is 'false', qt5 applications will not be accessible unless QT_LINUX_ACCESSIBILITY_ALWAYS_ON is set to 1

Layer enabling
WARN: screen-reader-enabled is not set in gsettings, use
      gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true
      to enable it
No such schema “org.mate.interface”
WARN: MATE accessibility is not set in gsettings, use
      gsettings set org.mate.interface accessibility true
      to enable it
PASS: GTK_MODULES contains gail
PASS: GTK_MODULES contains atk-bridge
PASS: QT_ACCESSIBILITY is set to 1
WARN: GNOME_ACCESSIBILITY is set to '', mozilla applications will not be accessible unless IsEnabled is set to true (as typically set by starting orca, but not accerciser etc.)
WARN: ACCESSIBILITY_ENABLED is set to '', chrome applications will not be accessible

**Comment by dr-ni** [comment]
can you try:
gsettings set org.mate.interface accessibility true
and check again

**Comment by gnulinux666** [comment]
No such schema “org.mate.interface”

**Comment by dr-ni** [comment]
on which?

**Comment by gnulinux666** [comment]
both

**Comment by dr-ni** [comment]
may be you can try installing LXQT on 24.04

**Comment by gnulinux666** [comment]
ok maybe conflict with Gnome desktop so I am installing lubuntu 24.04 on virtualbox

**Comment by gnulinux666** [comment]
```
Info
INFO: session type 'x11'
INFO: VT '2'
INFO: session desktop 'LXQt'
INFO: current desktop 'LXQt'
INFO: display variables DISPLAY=:0 

Packages
PASS: at-spi2-core installed
PASS: libgail-common installed
FAIL: libatk-adaptor not installed, GTK2 applications will not be accessible
FAIL: qt-at-spi not installed, Qt4 applications will not be accessible
FAIL: libatk-wrapper-java not installed, Java Swing applications will not be accessible

Running environment
PASS: at-spi-bus-launcher is running as user lubuntu24
PASS: at-spi2-registryd is running as user lubuntu24
FAIL: mismatch between $DBUS_SESSION_BUS_ADDRESS (unix:path=/run/user/1000/bus) and well-known path /home/lubuntu24/.dbus/session-bus/6a23eqwefe34dc4afa3082qqwwd8a656008-0 ()
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=c0273be88c01ugre0160462566857dad from session dbus
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=c0273trerr5d14tersd0462566857dad from root window
PASS: accessibility buses from session dbus and from root window match
WARN: org.a11y.Status IsEnabled is 'false', mozilla applications will not be accessible unless GNOME_ACCESSIBILITY is set to 1
WARN: org.a11y.Status ScreenReaderEnabled is 'false', qt5 applications will not be accessible unless QT_LINUX_ACCESSIBILITY_ALWAYS_ON is set to 1

Layer enabling
WARN: screen-reader-enabled is not set in gsettings, use
      gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true
      to enable it
No such schema “org.mate.interface”
WARN: MATE accessibility is not set in gsettings, use
      gsettings set org.mate.interface accessibility true
      to enable it
WARN: GTK_MODULES does not contain gail, GTK2 applications may not be accessible
WARN: GTK_MODULES does not contain atk-bridge, GTK2 applications may not be accessible
PASS: QT_ACCESSIBILITY is set to 1
WARN: GNOME_ACCESSIBILITY is set to '', mozilla applications will not be accessible unless IsEnabled is set to true (as typically set by starting orca, but not accerciser etc.)
WARN: ACCESSIBILITY_ENABLED is set to '', chrome applications will not be accessible

```
now I am installing your onboard

**Comment by gnulinux666** [comment]
mousetweaks got error I sent and onboard core dump on lubuntu 24.04

**Comment by dr-ni** [comment]
switch to gtk

**Comment by gnulinux666** [comment]
I checked all key stroke but on LXQt same as gnome desktop persian language didn't work

**Comment by dr-ni** [comment]
puh, I have now no idea now
try to find some help for at-spi2,  I think here is the problem with the persian suggestion.

**Comment by gnulinux666** [comment]
Thanks a lot

**Comment by dr-ni** [comment]
is hunspell-fa installed?

**Comment by gnulinux666** [comment]
there is no hunspell-fa for installing so I installed hunspell-ar and Arabic language didn't work

**Comment by dr-ni** [comment]
can you pull again, XInput should be working again...

**Comment by gnulinux666** [comment]
I've done and I confirmed XInput is working, Thank you.

**Comment by gnulinux666** [comment]
I find another issue ,May I ask you to check it? , autosugestion is working on firefox but is not working on google-chrome

**Comment by dr-ni** [comment]
can you show me with recordmydesktop?

**Comment by dr-ni** [comment]
...also again pull some more changes

**Comment by gnulinux666** [comment]
https://github.com/user-attachments/assets/13edceb4-211b-4cbb-9d25-a5a9267f42cf

**Comment by dr-ni** [comment]
Can you send me again
```
git clone https://git.debian.org/git/pkg-a11y/check-a11y
cd check-a11y
./troubleshoot
```

**Comment by dr-ni** [comment]
you can try also `dbus-send --print-reply --type=method_call --dest=org.a11y.Bus /org/a11y/bus org.freedesktop.DBus.Properties.Set string:org.a11y.Status string:IsEnabled variant:boolean:true` in terminal

**Comment by dr-ni** [comment]
and try to start chrome like this: `ACCESSIBILITY_ENABLED=1 chrome --force-renderer-accessibility`

**Comment by gnulinux666** [comment]
```
./troubleshoot 
Info
INFO: session type 'x11'
INFO: VT ''
INFO: session desktop 'ubuntu-xorg'
INFO: current desktop 'ubuntu:GNOME'
INFO: display variables DISPLAY=:0 

Packages
PASS: at-spi2-core installed
PASS: libgail-common installed
PASS: libatk-adaptor installed
FAIL: qt-at-spi not installed, Qt4 applications will not be accessible
PASS: libatk-wrapper-java installed

Running environment
PASS: at-spi-bus-launcher is running as user linux
PASS: at-spi2-registryd is running as user linux
FAIL: mismatch between $DBUS_SESSION_BUS_ADDRESS (unix:path=/run/user/1000/bus) and well-known path /home/linux/.dbus/session-bus/23035534dfba7984ac9336634c070085-0 ()
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=112b1930474ca9d3cdc5676d669tu33f from session dbus
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=112b1930474ca9d3cdc5676d669tu33f from root window
PASS: accessibility buses from session dbus and from root window match
PASS: org.a11y.Status IsEnabled is true
WARN: org.a11y.Status ScreenReaderEnabled is 'false', qt5 applications will not be accessible unless QT_LINUX_ACCESSIBILITY_ALWAYS_ON is set to 1

Layer enabling
WARN: screen-reader-enabled is not set in gsettings, use
      gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true
      to enable it
No such schema “org.mate.interface”
WARN: MATE accessibility is not set in gsettings, use
      gsettings set org.mate.interface accessibility true
      to enable it
PASS: GTK_MODULES contains gail
PASS: GTK_MODULES contains atk-bridge
PASS: QT_ACCESSIBILITY is set to 1
WARN: GNOME_ACCESSIBILITY is set to '', mozilla applications will not be accessible unless IsEnabled is set to true (as typically set by starting orca, but not accerciser etc.)
WARN: ACCESSIBILITY_ENABLED is set to '', chrome applications will not be accessible
```
dbus-send --print-reply --type=method_call --dest=org.a11y.Bus /org/a11y/bus org.freedesktop.DBus.Properties.Set string:org.a11y.Status string:IsEnabled variant:boolean:true
```
method return time=1721647257.473365 sender=:1.14 -> destination=:1.926 serial=112 reply_serial=2
```

**Comment by dr-ni** [comment]
did you start chrome from terminal?

 `ACCESSIBILITY_ENABLED=1 chrome --force-renderer-accessibility`

is it now working?

**Comment by gnulinux666** [comment]
I checked `ACCESSIBILITY_ENABLED=1 google-chrome --force-renderer-accessibility` but autosugestion didn't work

**Comment by dr-ni** [comment]
can you check `ACCESSIBILITY_ENABLED=1 ./troubleshoot`

**Comment by gnulinux666** [comment]
```
ACCESSIBILITY_ENABLED=1 ./troubleshoot
Info
INFO: session type 'x11'
INFO: VT ''
INFO: session desktop 'ubuntu-xorg'
INFO: current desktop 'ubuntu:GNOME'
INFO: display variables DISPLAY=:0 

Packages
PASS: at-spi2-core installed
PASS: libgail-common installed
PASS: libatk-adaptor installed
FAIL: qt-at-spi not installed, Qt4 applications will not be accessible
PASS: libatk-wrapper-java installed

Running environment
PASS: at-spi-bus-launcher is running as user linux
PASS: at-spi2-registryd is running as user linux
FAIL: mismatch between $DBUS_SESSION_BUS_ADDRESS (unix:path=/run/user/1000/bus) and well-known path /home/linux/.dbus/session-bus/23035534dfba7984ac9336634c070085-0 ()
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=112b1930474ca9d3cdc5676d669tu33f from session dbus
PASS: got accessibility bus unix:path=/run/user/1000/at-spi/bus_0,guid=112b1930474ca9d3cdc5676d669tu33f from root window
PASS: accessibility buses from session dbus and from root window match
PASS: org.a11y.Status IsEnabled is true
WARN: org.a11y.Status ScreenReaderEnabled is 'false', qt5 applications will not be accessible unless QT_LINUX_ACCESSIBILITY_ALWAYS_ON is set to 1

Layer enabling
WARN: screen-reader-enabled is not set in gsettings, use
      gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true
      to enable it
No such schema “org.mate.interface”
WARN: MATE accessibility is not set in gsettings, use
      gsettings set org.mate.interface accessibility true
      to enable it
PASS: GTK_MODULES contains gail
PASS: GTK_MODULES contains atk-bridge
PASS: QT_ACCESSIBILITY is set to 1
WARN: GNOME_ACCESSIBILITY is set to '', mozilla applications will not be accessible unless IsEnabled is set to true (as typically set by starting orca, but not accerciser etc.)
```

**Comment by dr-ni** [comment]
I do not know the problem, should be working...
can you install chromium-browser `sudo apt install chromium-browser`
and check this again?

**Comment by gnulinux666** [comment]
Do you have google-chrome or chromium? Is it working for you?  which one?

**Comment by dr-ni** [comment]
I have chromium-browser and it is working

**Comment by gnulinux666** [comment]
normal running is't working but with `ACCESSIBILITY_ENABLED=1 chromium-browser  --force-renderer-accessibility` autosugestion is working on chromium-browser

**Comment by dr-ni** [comment]
I'm using mate desktop with `gsettings set org.mate.interface accessibility true` maybe you should switch to mate

**Comment by gnulinux666** [comment]
Thanks for your suggestion, by the way what is your linux distribution ?

**Comment by dr-ni** [comment]
ubuntu mate

**Comment by dr-ni** [comment]
is persian now working with XInput?

**Comment by gnulinux666** [comment]
No !

**Comment by dr-ni** [comment]
With keystroke-generator auto?
Please first pull and rebuild

**Comment by dr-ni** [comment]
Chromium and Chrome:
```
For performance reasons Chromium waits until it detects the presence of assistive technology before enabling full support for accessibility APIs.

Windows: Chrome calls NotifyWinEvent with EVENT_SYSTEM_ALERT and the custom object id of 1. If it subsequently receives a WM_GETOBJECT call for that custom object id, it assumes that assistive technology is running.

Mac OS X: Chromium turns on or off accessibility support based on whether it sees a client, such as VoiceOver, has set the AXEnhancedUserInterface attribute on the main application window.

To override:

Start Chrome with this flag: --force-renderer-accessibility
Or, visit this url to turn it on from within Chrome: chrome://accessibility
```

**Comment by dr-ni** [comment]
![Screenshot at 2024-07-23 02-55-59](https://github.com/user-attachments/assets/5d69b98f-be8d-4ea7-8b0f-1206d04dc72f)

**Comment by gnulinux666** [comment]
awesome , Now persian language is working

**Comment by dr-ni** [comment]
what was the reason?
the keystroke-generator or my code update?

**Comment by gnulinux666** [comment]
after updating your code and changing keystroke-genarator to auto

**Comment by dr-ni** [comment]
can you now check with at-spi again?

**Comment by gnulinux666** [comment]
Not working with at-spi

**Comment by dr-ni** [comment]
ok, thank you
